### ISSUE TITLE
Not Kaggle banning Gradio?

### ISSUE THREAD

**Issue by MinatoIsuki** [ardha27/AI-Song-Cover-RVC#19]
![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/102457568/60972b78-f21f-43f4-8c17-268f5e9e0e63)
Sometimes Gradio did generate public link, but the code is automatically get Ctrl+C then disconnects from runtime.

**Comment by ardha27** [comment]
they ban webui from kaggle
![Uploading image.png…]()
