### ISSUE TITLE
New Song AI Cover

### ISSUE THREAD

**Issue by Dys2X** [ardha27/AI-Song-Cover-RVC#26]
Hey, does anyone know when it'll be possible again to create new AI Cover? It's so sad that it has been removed by google. Is there any other way? Because it's standing there that it has been removed for free Users. Can i become a premium user to use it again? 
I love your work and i've got a lot of fans i don't want to disappoint.

**Comment by MinatoIsuki** [comment]
- You can still create a new AI cover (With no WebUI notebook), RVC is **NOT** banned, Gradio is.
- What do you mean of "a premium user"? Colab Pro?

**Comment by Dys2X** [comment]
Really? Which one i have to choose on this site?
https://colab.research.google.com/drive/1r4IRL0UA7JEoZ0ZK8PKfMyTIBHKpyhcw#scrollTo=Sb5fzhzEXK8X 
Because theres always Error

**Comment by MinatoIsuki** [comment]
> Really? Which one i have to choose on this site? https://colab.research.google.com/drive/1r4IRL0UA7JEoZ0ZK8PKfMyTIBHKpyhcw#scrollTo=Sb5fzhzEXK8X Because theres always Error

Big error. A huge one.
![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/102457568/4fc50703-3726-4309-9cab-bf91e6582ffa)
Your notebook is tripping off Google ToS thing for Gradio or asset download. Let me see what caused Colab to trip off.

**Comment by MinatoIsuki** [comment]
Doesn't take me long to find the issue.
Please remove this block and take it to another notebook.
![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/102457568/2b12dae7-0394-42e6-ba3d-ce9c139981e9)

**Comment by Dys2X** [comment]
![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/146621367/3c6178b8-3462-4690-a0fa-056b2ced24eb)

**Comment by Dys2X** [comment]
> Doesn't take me long to find the issue. Please remove this block and take it to another notebook. ![image](https://user-images.githubusercontent.com/102457568/271816221-2b12dae7-0394-42e6-ba3d-ce9c139981e9.png)

Sorry, i'm a big noob and don't know anything about coding. What do i have to remove and take it where?

**Comment by Dys2X** [comment]
![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/146621367/cca1aa6e-e720-4578-8441-41c0818cde55)

**Comment by MinatoIsuki** [comment]
Remove the `OR Open the GUI` block from this notebook and make a new notebook, then paste the `OR Open the GUI` block in.

> > Doesn't take me long to find the issue. Please remove this block and take it to another notebook. ![image](https://user-images.githubusercontent.com/102457568/271816221-2b12dae7-0394-42e6-ba3d-ce9c139981e9.png)
> 
> Sorry, i'm a big noob and don't know anything about coding. What do i have to remove and take it where?

**Comment by MinatoIsuki** [comment]
> ![image](https://user-images.githubusercontent.com/146621367/271816345-cca1aa6e-e720-4578-8441-41c0818cde55.png)

Mount Drive failed. You might have disabled pop-up or something since I can still connect my Drive in the runtime.

**Comment by Dys2X** [comment]
oh wait. Maybe it's the wrong Google Account. On the top right. I changed to the Google Account i sign in when i connect it to Google Drive. 
For now it seems to work 😁 Thanks a lot!!! 
![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/146621367/4498a3e2-aea7-4f4b-9a61-4aa263ae557d)

**Comment by MinatoIsuki** [comment]
No problem!
*Please close this issue if there is no problem left, else, send here.*

**Comment by Dys2X** [comment]
Sure, again.. thank you!!

**Comment by Dys2X** [comment]
@MinatoIsuki 
Okay.. after 3 Songs i was disconnected. After reloading the Site, nothing happens. 
![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/146621367/a8897aa7-d150-4df2-902a-0a75d8f95cf7)

**Comment by MinatoIsuki** [comment]
Of course, you use WebUI (which is banned) so that's something you can expected.
You can use the no WebUI one (I think it's already in your notebook?) to use. You won't have a nice UI though.

**Comment by Dys2X** [comment]
Eh no. You mean on my physical Notebook(Computer) or on the digital "Notebook" thing? 
I don't even know where to get the no WebUI thing 😂 - Is there an alternative to the "not nice UI"? 
So if this is something i can expect, means that sometimes it can work and sometimes it doesn't?
Sorry, i hope i don't bother you with my noob questions. I really appreciate your help.

**Comment by MinatoIsuki** [comment]
> Eh no. You mean on my physical Notebook(Computer) or on the digital "Notebook" thing? I don't even know where to get the no WebUI thing 😂 - Is there an alternative to the "not nice UI"? So if this is something i can expect, means that sometimes it can work and sometimes it doesn't? Sorry, i hope i don't bother you with my noob questions. I really appreciate your help.

- This is a Jupyter **notebook**. (.ipynb), and you are opening it with Colab (basically borrowing Google's computer)
- Notice how the code output a public link? That is Gradio, or WebUI.
   ![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/102457568/6385aeda-d7de-4d34-96ac-2eac6b2bddbf)

- In your notebook, the block listed from 1 to 4 is no WebUI.
  ![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/102457568/38b9375c-59ce-45fc-b38d-644bb8213691)

- You have to add a bunch of `#@markdown` for the "not nice UI". You have no choice left.
- It works then doesn't. Only happens if you use WebUI.
