### ISSUE TITLE
Hina mod rvc free error?

### ISSUE THREAD

**Issue by Bilzz-cgi** [ardha27/AI-Song-Cover-RVC#45]
Idk whats wrong with Hina mod RVC free today, but it was fine on July 22 since the last time I ran the program.
I got code results like this on Run WebUi cell

"Traceback (most recent call last):
  File "/content/drive/MyDrive/Hina_RVC/src/webui.py", line 9, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'"

The result is that the Gradio link which usually appears does not appear this time
I thought that the space on my Google Drive was full, so I ran the code using a different account but still, the gradio link doesn't appear as usual

**Comment by ardha27** [comment]
fixed, try it again dont forget to give a start to the repo ✌️

**Comment by Bilzz-cgi** [comment]
Yay!
Thats work!!
Tysm sir

**Comment by Bilzz-cgi** [comment]
Yeah its work!!
but it requires more time than the previous one
