### ISSUE TITLE
Need upgrade 

### ISSUE THREAD

**Issue by Bilzz-cgi** [ardha27/AI-Song-Cover-RVC#50]
Today I got a new issue on Hina mod ai cover gen in RunWebui cell

IMPORTANT: You are using gradio version 3.39.0, however version 4.29.0 is available, please upgrade.

**Comment by Bilzz-cgi** [comment]
and also, the cover results don't appear on the webui...
I have tried several different songs but the result is still the same

**Comment by ardha27** [comment]
Its already updated. In order to update it, you need to delete your old AICoverGen dir on your drive

**Comment by Bilzz-cgi** [comment]
Tysm sir!
