### ISSUE TITLE
New Issue after update 

### ISSUE THREAD

**Issue by Bilzz-cgi** [ardha27/AI-Song-Cover-RVC#51]
after waiting a couple minutes after I ran the collab
i got result like this on gradio

504 Gateway Time-out 

Ofc i already deleted the old covergen files as instructed

**Comment by Bilzz-cgi** [comment]
and also, i still get the same result after trying with an account that still has the old files

**Comment by ardha27** [comment]
Can you add screenshot?

**Comment by Bilzz-cgi** [comment]
![Screenshot_2024-08-28-22-04-54-595_com android chrome](https://github.com/user-attachments/assets/58158d27-348b-4b8b-8d60-b045268e99e9)
here we go

**Comment by ardha27** [comment]
![image](https://github.com/user-attachments/assets/9b7ed674-f2e0-422e-b5d3-087c22ed9825)
https://status.gradio.app
the gradio server is currently down, we only can wait til they fix it

**Comment by Bilzz-cgi** [comment]
i see, that makes sense
