### ISSUE TITLE
EasyGUI can no longer be found.

### ISSUE THREAD

**Issue by Alucard-Elric** [ardha27/AI-Song-Cover-RVC#52]
I can no longer access the EasyGUI, it just brings up Page Not Found. Is it down temporarily while the code is patched up, is the link different, or is it just... gone?

This is how I accessed it previously:
https://colab.research.google.com/drive/1r4IRL0UA7JEoZ0ZK8PKfMyTIBHKpyhcw#scrollTo=Sb5fzhzEXK8X

**Comment by ardha27** [comment]
https://github.com/ardha27/AI-Song-Cover-RVC/blob/main/easyGUI%F0%9F%93%B1_4_20_24.ipynb

**Comment by Alucard-Elric** [comment]
Ah! Thank you much, however, the code itself does seem to still have an issue. When I run section "open the EasyGui" It kick backs this error

/content/RVC
Error loading .ipynb_checkpoints
Traceback (most recent call last):
  File "/content/RVC/demo.py", line 1, in <module>
    from original import *
  File "/content/RVC/original.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by JC2311** [comment]
The Gradio live train model is showing an error. Can this issue be resolved?
