### ISSUE TITLE
Connection time out on hina aicovergen 

### ISSUE THREAD

**Issue by Bilzz-cgi** [ardha27/AI-Song-Cover-RVC#56]
hina aicovergen was running normally until last night, today I always get a pop-up notification when running gradio live, just like "connection time out" when i try to install new model or generate some ai cover

I also got the same result when trying with a different account

and also i got result like this on RunWebui cell 
"If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion."

**Comment by Bilzz-cgi** [comment]
is it possible to fix?

**Comment by ardha27** [comment]
https://discuss.huggingface.co/t/new-gradio-space-connection-errored-out/105509/3

**Comment by Bilzz-cgi** [comment]
Tysm sir!
That helped me so much
