### ISSUE TITLE
Run web gradio

### ISSUE THREAD

**Issue by HengkyZiliwu** [ardha27/AI-Song-Cover-RVC#7]
link gradionya ga muncul bang untuk yang versi v2

**Comment by Darelllf** [comment]
> link gradionya ga muncul bang untuk yang versi v2

@HengkyZiliwu pake colab gw sementaa, gw udah benerin erornya
https://colab.research.google.com/drive/1wMD60_imE9wft5cspFsoIHCIo6mJQKxo?usp=sharing

**Comment by HengkyZiliwu** [comment]
ok thank bg
